#!/usr/bin/sh

# Composite manager
xcompmgr -c &

# Wallpaper manager initialization
nitrogen --restore &

# Terminal initialization
urxvtd -q -o -f &

# Polybar at top of desktop start
[[ $(command -v polybar) ]] && sh ~/.bin/bar_start &

# Tint2 button panel at the down of desktop start
tint2 -c ~/.config/tint2/button.tint2rc
