#!/usr/bin/sh

# Screen locker
light-locker --lock-on-suspend --lock-on-lid &

# Composite manager
xcompmgr -c &

# Wallpaper manager initialization
nitrogen --restore &

# Terminal initialization
urxvtd -q -o -f &
sh $HOME/.bin/term_bg.sh &

# Polybar at top of desktop start
[[ $(command -v polybar) ]] && sh $HOME/.bin/bar_start.sh &

# Tint2 button panel at down of desktop start
tint2 -c ~/.config/tint2/button.tint2rc &

# Tint2 tray
tint2 -c ~/.config/tint2/hide_tray.tint2rc &

# System tray applets
nm-applet #Network-manager
